### ISSUE TITLE
Texture tweaks

### ISSUE THREAD

**Issue by Heamaci** [RedLime/DetailArmorBar#9]
I made all the armor icons more consistent with the netherite one. You can use them if you like :)
![armorstuff](https://user-images.githubusercontent.com/67716228/131209903-1950bbc2-d724-4e4e-9506-adf8ce22bead.png)

**Comment by Heamaci** [comment]
I also have a small suggestion. There is some overlapping with the armor slot icons and the elytra. Move the elytra icon to the left of the armor bar slightly separated. 

like this:
![130203813-e96f7bb0-12b6-4485-a9d7-ebc29496049a](https://user-images.githubusercontent.com/67716228/131210006-7643236d-8a89-45ca-8e43-a95abbf5a685.png)

**Comment by RedLime** [comment]
Updated texture in v2.4!

Also, there is currently only one special item bar in the DAB, Elytra, but if other developers use the API to add it, this could be confusing.

Thanks for your contribute! :>

**Comment by catgirldoll** [comment]
The issue is that these textures are _less consistent with vanilla_.
Vanilla 1.17.1 `icons.png`:
![image](https://user-images.githubusercontent.com/20545957/133920957-d7525b4a-a886-4b1c-842e-e8f63347ae01.png)

DAB V2.3:
![image](https://user-images.githubusercontent.com/20545957/133921007-27598aae-97e7-4581-85c6-3eb82bc87222.png)

DAB V2.4:
![image](https://user-images.githubusercontent.com/20545957/133921023-9a978921-d065-45f9-9d6b-cd410eb3637c.png)

V2.3 sprites could use tweaking, but V2.4 textures look irrefutably _less vanilla_. That is to say, V2.4 sprites are more detailed and more stylized than the vanilla sprites which as a result breaks from the mod's vanilla+ feel. 

Whilst I do believe V2.4 textures look subjectively _better_, I would propose the following version as a drop-in replacement to bring both consistency and a vanilla feel:
![image](https://user-images.githubusercontent.com/20545957/133921813-92bce1cb-2b7e-4d33-bf72-1fa180fdd27e.png)

Usable version:
![v2 5](https://user-images.githubusercontent.com/20545957/133921825-7691440a-080f-4be7-a29a-a0f4c9ffb249.png)

**Comment by RedLime** [comment]
that's right. I had the same thought while using my mod.
So I will add vanilla style texture option in version 2.4.
And I think your texture will be useful for that.

**Comment by catgirldoll** [comment]
Edit: shinier gold, _technically_ smaller file size (by one single byte)
![v2.5.1-preview](https://user-images.githubusercontent.com/20545957/134109100-3b4d2d58-8fb3-47b6-a1df-70a445095208.png)
![v2.5.1](https://user-images.githubusercontent.com/20545957/134109007-c8c7181d-39e6-4421-b5e8-80f634d75770.png)

**Comment by RedLime** [comment]
> Edit: shinier gold, _technically_ smaller file size (by one single byte)
> ![v2.5.1-preview](https://user-images.githubusercontent.com/20545957/134109100-3b4d2d58-8fb3-47b6-a1df-70a445095208.png)
> ![v2.5.1](https://user-images.githubusercontent.com/20545957/134109007-c8c7181d-39e6-4421-b5e8-80f634d75770.png)

Could you please change the texture of the leather to white?

**Comment by RedLime** [comment]
Patched in 2.5

**Comment by snessim** [comment]
Only just saw your request - I'll change the leather sprite to Mojang's normal white/greyscale not-yet-colormapped textures when I next get a chance to be at my computer (probably tomorrow). Do you need a colormap image?
